apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
    - image: tsunami-controller
      context: .
  local:
    useBuildkit: true
deploy:
  kustomize:
    path: patches
#  kubectl:
#    manifests:
#      - patches
#    flags:
#      apply:
#        - -k
