apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - crd/tsunami.kaidotorg.github.io_scans.yaml
  - cluster_role.yaml
  - cluster_role_binding.yaml
  - deployment.yaml
  - pod_disruption_budget.yaml
  - role.yaml
  - role_binding.yaml
  - service_account.yaml
